[build]
  publish = "."
  command = "echo 'No build step needed for static site'"

[[redirects]]
  from = "/"
  to = "/Acceuil.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/Acceuil.html"
  status = 404